#cloud-config
package_update: true
package_upgrade: true
packages:
  - net-tools
  - iperf3
  - wget
  - curl
runcmd:
  - systemctl enable --now iperf3
  - curl -fsSL https://tailscale.com/install.sh | sh
  - curl -s https://deb.frrouting.org/frr/keys.gpg | tee /usr/share/keyrings/frrouting.gpg > /dev/null
  - echo "deb [signed-by=/usr/share/keyrings/frrouting.gpg] https://deb.frrouting.org/frr $(lsb_release -s -c) frr-stable" | tee -a /etc/apt/sources.list.d/frr.list
  - apt update && apt install -y frr frr-pythontools
  - |
    cat << EOF | tee -a /etc/sysctl.conf
    net.ipv4.ip_forward = 1
    net.ipv6.conf.all.forwarding = 1
    EOF
  - sysctl -p
  - |
    DEFAULT_IFACE=$(ip route | grep default | awk '{print $5}' | head -1)
    PRIVATE_SUBNET=$(ip route | grep 'proto kernel scope link' | grep -E '^(10\.|172\.(1[6-9]|2[0-9]|3[01])\.|192\.168\.)' | grep -v "$DEFAULT_IFACE" | awk '{print $1}' | head -1)

    if [ -n "$PRIVATE_SUBNET" ]; then
      INTERFACE=$(ip route | grep "$PRIVATE_SUBNET" | awk '{print $3}' | head -1)
      SUBNET="$PRIVATE_SUBNET"
    else
      PRIVATE_SUBNET=$(ip route | grep 'proto kernel scope link' | grep -E '^(10\.|172\.(1[6-9]|2[0-9]|3[01])\.|192\.168\.)' | awk '{print $1}' | head -1)
      if [ -n "$PRIVATE_SUBNET" ]; then
        INTERFACE="$DEFAULT_IFACE"
        SUBNET="$PRIVATE_SUBNET"
      else
        INTERFACE="$DEFAULT_IFACE"
        SUBNET=$(ip route | grep $INTERFACE | grep -v default | grep -v via | awk '{print $1}' | head -1)
      fi
    fi
    sed -i 's/^zebra=.*/zebra=yes/'   /etc/frr/daemons
    sed -i 's/^ospfd=.*/ospfd=yes/'   /etc/frr/daemons
    cat << EOF > /etc/frr/frr.conf
    frr version 8.4
    frr defaults traditional
    hostname gateway-${REGION}
    log syslog
    interface $INTERFACE
     ip ospf area 0
    router ospf
     network $SUBNET area 0
     redistribute kernel
     redistribute static
     redistribute connected metric 10 subnets
    line vty
    EOF
  - systemctl restart frr
  - systemctl enable frr
  - iptables -A INPUT -p ospf -j ACCEPT
  - ufw allow 5201
  - |
    cat << 'EOF' > /usr/local/bin/set-ospf-rule.sh
    #!/bin/bash
    sleep 10
    iptables -C INPUT -p ospf -j ACCEPT || iptables -A INPUT -p ospf -j ACCEPT
    # sync tailscale routes
    ip route show table 52 | while read -r ROUTE; do
    ip route replace $ROUTE
    done
    EOF
  - chmod +x /usr/local/bin/set-ospf-rule.sh
  - (crontab -l 2>/dev/null; echo "@reboot /usr/local/bin/set-ospf-rule.sh") | crontab - 
